[workspace]
members = [
	"cardano-embedded-sdk",
	"rust-ed25519-bip32",
    "qemu-example",
	"nrf52-demo/demo-client",
	"nrf52-demo/embedano-device",
    "device-example/device",
    "device-example/host",
]
