[workspace]
members = [
	"cardano-embedded-sdk",
	"rust-ed25519-bip32",
	"examples/nrf52-demo/demo-client",
	"examples/nrf52-demo/embedano-device",
	"examples/stm32f-example/device",
  "examples/stm32f-example/host",
  "examples/qemu-example",
]
